// Code generated by go-swagger; DO NOT EDIT.

package fleet_country

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams object
// with the default values initialized.
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams() *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithTimeout creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams{

		timeout: timeout,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithContext creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithContext(ctx context.Context) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams{

		Context: ctx,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithHTTPClient creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams{
		HTTPClient: client,
	}
}

/*DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams contains all the parameters to send to the API endpoint
for the delete fleet tenant tenant ID brand brand ID country country ID systemproperties operation typically these are written to a http.Request
*/
type DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams struct {

	/*BrandID*/
	BrandID string
	/*CountryID*/
	CountryID string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithContext(ctx context.Context) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBrandID adds the brandID to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithBrandID(brandID string) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithCountryID adds the countryID to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithCountryID(countryID string) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetCountryID(countryID)
	return o
}

// SetCountryID adds the countryId to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetCountryID(countryID string) {
	o.CountryID = countryID
}

// WithTenantID adds the tenantID to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithTenantID(tenantID string) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the delete fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param countryId
	if err := r.SetPathParam("countryId", o.CountryID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
