// Code generated by go-swagger; DO NOT EDIT.

package fleet_country

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams object
// with the default values initialized.
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams() *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParamsWithTimeout creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParamsWithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams{

		timeout: timeout,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParamsWithContext creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParamsWithContext(ctx context.Context) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams{

		Context: ctx,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParamsWithHTTPClient creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParamsWithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams{
		HTTPClient: client,
	}
}

/*DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams contains all the parameters to send to the API endpoint
for the delete fleet tenant tenant ID brand brand ID country country ID system properties URL operation typically these are written to a http.Request
*/
type DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams struct {

	/*BrandID*/
	BrandID string
	/*CountryID*/
	CountryID string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) WithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) WithContext(ctx context.Context) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) WithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBrandID adds the brandID to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) WithBrandID(brandID string) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithCountryID adds the countryID to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) WithCountryID(countryID string) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams {
	o.SetCountryID(countryID)
	return o
}

// SetCountryID adds the countryId to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) SetCountryID(countryID string) {
	o.CountryID = countryID
}

// WithTenantID adds the tenantID to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) WithTenantID(tenantID string) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the delete fleet tenant tenant ID brand brand ID country country ID system properties URL params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDSystemPropertiesURLParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param countryId
	if err := r.SetPathParam("countryId", o.CountryID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
