// Code generated by go-swagger; DO NOT EDIT.

package fleet_country

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams creates a new GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams object
// with the default values initialized.
func NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams() *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithTimeout creates a new GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams{

		timeout: timeout,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithContext creates a new GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithContext(ctx context.Context) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams{

		Context: ctx,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithHTTPClient creates a new GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParamsWithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams{
		HTTPClient: client,
	}
}

/*GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams contains all the parameters to send to the API endpoint
for the get fleet tenant tenant ID brand brand ID country country ID systemproperties operation typically these are written to a http.Request
*/
type GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams struct {

	/*BrandID*/
	BrandID string
	/*CountryID*/
	CountryID string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithContext(ctx context.Context) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBrandID adds the brandID to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithBrandID(brandID string) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithCountryID adds the countryID to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithCountryID(countryID string) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetCountryID(countryID)
	return o
}

// SetCountryID adds the countryId to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetCountryID(countryID string) {
	o.CountryID = countryID
}

// WithTenantID adds the tenantID to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WithTenantID(tenantID string) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get fleet tenant tenant ID brand brand ID country country ID systemproperties params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDSystempropertiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param countryId
	if err := r.SetPathParam("countryId", o.CountryID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
