// Code generated by go-swagger; DO NOT EDIT.

package inventory_manufacturer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetInventoryManufacturerManufacturerIDParams creates a new GetInventoryManufacturerManufacturerIDParams object
// with the default values initialized.
func NewGetInventoryManufacturerManufacturerIDParams() *GetInventoryManufacturerManufacturerIDParams {
	var ()
	return &GetInventoryManufacturerManufacturerIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInventoryManufacturerManufacturerIDParamsWithTimeout creates a new GetInventoryManufacturerManufacturerIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInventoryManufacturerManufacturerIDParamsWithTimeout(timeout time.Duration) *GetInventoryManufacturerManufacturerIDParams {
	var ()
	return &GetInventoryManufacturerManufacturerIDParams{

		timeout: timeout,
	}
}

// NewGetInventoryManufacturerManufacturerIDParamsWithContext creates a new GetInventoryManufacturerManufacturerIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInventoryManufacturerManufacturerIDParamsWithContext(ctx context.Context) *GetInventoryManufacturerManufacturerIDParams {
	var ()
	return &GetInventoryManufacturerManufacturerIDParams{

		Context: ctx,
	}
}

// NewGetInventoryManufacturerManufacturerIDParamsWithHTTPClient creates a new GetInventoryManufacturerManufacturerIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInventoryManufacturerManufacturerIDParamsWithHTTPClient(client *http.Client) *GetInventoryManufacturerManufacturerIDParams {
	var ()
	return &GetInventoryManufacturerManufacturerIDParams{
		HTTPClient: client,
	}
}

/*GetInventoryManufacturerManufacturerIDParams contains all the parameters to send to the API endpoint
for the get inventory manufacturer manufacturer ID operation typically these are written to a http.Request
*/
type GetInventoryManufacturerManufacturerIDParams struct {

	/*ManufacturerID*/
	ManufacturerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get inventory manufacturer manufacturer ID params
func (o *GetInventoryManufacturerManufacturerIDParams) WithTimeout(timeout time.Duration) *GetInventoryManufacturerManufacturerIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inventory manufacturer manufacturer ID params
func (o *GetInventoryManufacturerManufacturerIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inventory manufacturer manufacturer ID params
func (o *GetInventoryManufacturerManufacturerIDParams) WithContext(ctx context.Context) *GetInventoryManufacturerManufacturerIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inventory manufacturer manufacturer ID params
func (o *GetInventoryManufacturerManufacturerIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inventory manufacturer manufacturer ID params
func (o *GetInventoryManufacturerManufacturerIDParams) WithHTTPClient(client *http.Client) *GetInventoryManufacturerManufacturerIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inventory manufacturer manufacturer ID params
func (o *GetInventoryManufacturerManufacturerIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithManufacturerID adds the manufacturerID to the get inventory manufacturer manufacturer ID params
func (o *GetInventoryManufacturerManufacturerIDParams) WithManufacturerID(manufacturerID string) *GetInventoryManufacturerManufacturerIDParams {
	o.SetManufacturerID(manufacturerID)
	return o
}

// SetManufacturerID adds the manufacturerId to the get inventory manufacturer manufacturer ID params
func (o *GetInventoryManufacturerManufacturerIDParams) SetManufacturerID(manufacturerID string) {
	o.ManufacturerID = manufacturerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInventoryManufacturerManufacturerIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param manufacturerId
	if err := r.SetPathParam("manufacturerId", o.ManufacturerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
