// Code generated by go-swagger; DO NOT EDIT.

package inventory_manufacturer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetInventoryManufacturerParams creates a new GetInventoryManufacturerParams object
// with the default values initialized.
func NewGetInventoryManufacturerParams() *GetInventoryManufacturerParams {
	var ()
	return &GetInventoryManufacturerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInventoryManufacturerParamsWithTimeout creates a new GetInventoryManufacturerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInventoryManufacturerParamsWithTimeout(timeout time.Duration) *GetInventoryManufacturerParams {
	var ()
	return &GetInventoryManufacturerParams{

		timeout: timeout,
	}
}

// NewGetInventoryManufacturerParamsWithContext creates a new GetInventoryManufacturerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInventoryManufacturerParamsWithContext(ctx context.Context) *GetInventoryManufacturerParams {
	var ()
	return &GetInventoryManufacturerParams{

		Context: ctx,
	}
}

// NewGetInventoryManufacturerParamsWithHTTPClient creates a new GetInventoryManufacturerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInventoryManufacturerParamsWithHTTPClient(client *http.Client) *GetInventoryManufacturerParams {
	var ()
	return &GetInventoryManufacturerParams{
		HTTPClient: client,
	}
}

/*GetInventoryManufacturerParams contains all the parameters to send to the API endpoint
for the get inventory manufacturer operation typically these are written to a http.Request
*/
type GetInventoryManufacturerParams struct {

	/*NextToken*/
	NextToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get inventory manufacturer params
func (o *GetInventoryManufacturerParams) WithTimeout(timeout time.Duration) *GetInventoryManufacturerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inventory manufacturer params
func (o *GetInventoryManufacturerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inventory manufacturer params
func (o *GetInventoryManufacturerParams) WithContext(ctx context.Context) *GetInventoryManufacturerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inventory manufacturer params
func (o *GetInventoryManufacturerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inventory manufacturer params
func (o *GetInventoryManufacturerParams) WithHTTPClient(client *http.Client) *GetInventoryManufacturerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inventory manufacturer params
func (o *GetInventoryManufacturerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNextToken adds the nextToken to the get inventory manufacturer params
func (o *GetInventoryManufacturerParams) WithNextToken(nextToken *string) *GetInventoryManufacturerParams {
	o.SetNextToken(nextToken)
	return o
}

// SetNextToken adds the nextToken to the get inventory manufacturer params
func (o *GetInventoryManufacturerParams) SetNextToken(nextToken *string) {
	o.NextToken = nextToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetInventoryManufacturerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.NextToken != nil {

		// query param nextToken
		var qrNextToken string
		if o.NextToken != nil {
			qrNextToken = *o.NextToken
		}
		qNextToken := qrNextToken
		if qNextToken != "" {
			if err := r.SetQueryParam("nextToken", qNextToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
