// Code generated by go-swagger; DO NOT EDIT.

package software_version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSoftwarePackagePackageIDVersionParams creates a new GetSoftwarePackagePackageIDVersionParams object
// with the default values initialized.
func NewGetSoftwarePackagePackageIDVersionParams() *GetSoftwarePackagePackageIDVersionParams {
	var ()
	return &GetSoftwarePackagePackageIDVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSoftwarePackagePackageIDVersionParamsWithTimeout creates a new GetSoftwarePackagePackageIDVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSoftwarePackagePackageIDVersionParamsWithTimeout(timeout time.Duration) *GetSoftwarePackagePackageIDVersionParams {
	var ()
	return &GetSoftwarePackagePackageIDVersionParams{

		timeout: timeout,
	}
}

// NewGetSoftwarePackagePackageIDVersionParamsWithContext creates a new GetSoftwarePackagePackageIDVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSoftwarePackagePackageIDVersionParamsWithContext(ctx context.Context) *GetSoftwarePackagePackageIDVersionParams {
	var ()
	return &GetSoftwarePackagePackageIDVersionParams{

		Context: ctx,
	}
}

// NewGetSoftwarePackagePackageIDVersionParamsWithHTTPClient creates a new GetSoftwarePackagePackageIDVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSoftwarePackagePackageIDVersionParamsWithHTTPClient(client *http.Client) *GetSoftwarePackagePackageIDVersionParams {
	var ()
	return &GetSoftwarePackagePackageIDVersionParams{
		HTTPClient: client,
	}
}

/*GetSoftwarePackagePackageIDVersionParams contains all the parameters to send to the API endpoint
for the get software package package ID version operation typically these are written to a http.Request
*/
type GetSoftwarePackagePackageIDVersionParams struct {

	/*NextToken*/
	NextToken *string
	/*PackageID*/
	PackageID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get software package package ID version params
func (o *GetSoftwarePackagePackageIDVersionParams) WithTimeout(timeout time.Duration) *GetSoftwarePackagePackageIDVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get software package package ID version params
func (o *GetSoftwarePackagePackageIDVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get software package package ID version params
func (o *GetSoftwarePackagePackageIDVersionParams) WithContext(ctx context.Context) *GetSoftwarePackagePackageIDVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get software package package ID version params
func (o *GetSoftwarePackagePackageIDVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get software package package ID version params
func (o *GetSoftwarePackagePackageIDVersionParams) WithHTTPClient(client *http.Client) *GetSoftwarePackagePackageIDVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get software package package ID version params
func (o *GetSoftwarePackagePackageIDVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNextToken adds the nextToken to the get software package package ID version params
func (o *GetSoftwarePackagePackageIDVersionParams) WithNextToken(nextToken *string) *GetSoftwarePackagePackageIDVersionParams {
	o.SetNextToken(nextToken)
	return o
}

// SetNextToken adds the nextToken to the get software package package ID version params
func (o *GetSoftwarePackagePackageIDVersionParams) SetNextToken(nextToken *string) {
	o.NextToken = nextToken
}

// WithPackageID adds the packageID to the get software package package ID version params
func (o *GetSoftwarePackagePackageIDVersionParams) WithPackageID(packageID string) *GetSoftwarePackagePackageIDVersionParams {
	o.SetPackageID(packageID)
	return o
}

// SetPackageID adds the packageId to the get software package package ID version params
func (o *GetSoftwarePackagePackageIDVersionParams) SetPackageID(packageID string) {
	o.PackageID = packageID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSoftwarePackagePackageIDVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.NextToken != nil {

		// query param nextToken
		var qrNextToken string
		if o.NextToken != nil {
			qrNextToken = *o.NextToken
		}
		qNextToken := qrNextToken
		if qNextToken != "" {
			if err := r.SetQueryParam("nextToken", qNextToken); err != nil {
				return err
			}
		}

	}

	// path param packageId
	if err := r.SetPathParam("packageId", o.PackageID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
