// Code generated by go-swagger; DO NOT EDIT.

package driver_version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDriverPackagePackageIDVersionVersionIDBinaryParams creates a new DeleteDriverPackagePackageIDVersionVersionIDBinaryParams object
// with the default values initialized.
func NewDeleteDriverPackagePackageIDVersionVersionIDBinaryParams() *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams {
	var ()
	return &DeleteDriverPackagePackageIDVersionVersionIDBinaryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDriverPackagePackageIDVersionVersionIDBinaryParamsWithTimeout creates a new DeleteDriverPackagePackageIDVersionVersionIDBinaryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDriverPackagePackageIDVersionVersionIDBinaryParamsWithTimeout(timeout time.Duration) *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams {
	var ()
	return &DeleteDriverPackagePackageIDVersionVersionIDBinaryParams{

		timeout: timeout,
	}
}

// NewDeleteDriverPackagePackageIDVersionVersionIDBinaryParamsWithContext creates a new DeleteDriverPackagePackageIDVersionVersionIDBinaryParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDriverPackagePackageIDVersionVersionIDBinaryParamsWithContext(ctx context.Context) *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams {
	var ()
	return &DeleteDriverPackagePackageIDVersionVersionIDBinaryParams{

		Context: ctx,
	}
}

// NewDeleteDriverPackagePackageIDVersionVersionIDBinaryParamsWithHTTPClient creates a new DeleteDriverPackagePackageIDVersionVersionIDBinaryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDriverPackagePackageIDVersionVersionIDBinaryParamsWithHTTPClient(client *http.Client) *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams {
	var ()
	return &DeleteDriverPackagePackageIDVersionVersionIDBinaryParams{
		HTTPClient: client,
	}
}

/*DeleteDriverPackagePackageIDVersionVersionIDBinaryParams contains all the parameters to send to the API endpoint
for the delete driver package package ID version version ID binary operation typically these are written to a http.Request
*/
type DeleteDriverPackagePackageIDVersionVersionIDBinaryParams struct {

	/*PackageID*/
	PackageID string
	/*VersionID*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete driver package package ID version version ID binary params
func (o *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams) WithTimeout(timeout time.Duration) *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete driver package package ID version version ID binary params
func (o *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete driver package package ID version version ID binary params
func (o *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams) WithContext(ctx context.Context) *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete driver package package ID version version ID binary params
func (o *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete driver package package ID version version ID binary params
func (o *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams) WithHTTPClient(client *http.Client) *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete driver package package ID version version ID binary params
func (o *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPackageID adds the packageID to the delete driver package package ID version version ID binary params
func (o *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams) WithPackageID(packageID string) *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams {
	o.SetPackageID(packageID)
	return o
}

// SetPackageID adds the packageId to the delete driver package package ID version version ID binary params
func (o *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams) SetPackageID(packageID string) {
	o.PackageID = packageID
}

// WithVersionID adds the versionID to the delete driver package package ID version version ID binary params
func (o *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams) WithVersionID(versionID string) *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the delete driver package package ID version version ID binary params
func (o *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDriverPackagePackageIDVersionVersionIDBinaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param packageId
	if err := r.SetPathParam("packageId", o.PackageID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
