// Code generated by go-swagger; DO NOT EDIT.

package driver_version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDriverPackagePackageIDVersionVersionIDBinaryURLParams creates a new GetDriverPackagePackageIDVersionVersionIDBinaryURLParams object
// with the default values initialized.
func NewGetDriverPackagePackageIDVersionVersionIDBinaryURLParams() *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams {
	var ()
	return &GetDriverPackagePackageIDVersionVersionIDBinaryURLParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDriverPackagePackageIDVersionVersionIDBinaryURLParamsWithTimeout creates a new GetDriverPackagePackageIDVersionVersionIDBinaryURLParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDriverPackagePackageIDVersionVersionIDBinaryURLParamsWithTimeout(timeout time.Duration) *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams {
	var ()
	return &GetDriverPackagePackageIDVersionVersionIDBinaryURLParams{

		timeout: timeout,
	}
}

// NewGetDriverPackagePackageIDVersionVersionIDBinaryURLParamsWithContext creates a new GetDriverPackagePackageIDVersionVersionIDBinaryURLParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDriverPackagePackageIDVersionVersionIDBinaryURLParamsWithContext(ctx context.Context) *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams {
	var ()
	return &GetDriverPackagePackageIDVersionVersionIDBinaryURLParams{

		Context: ctx,
	}
}

// NewGetDriverPackagePackageIDVersionVersionIDBinaryURLParamsWithHTTPClient creates a new GetDriverPackagePackageIDVersionVersionIDBinaryURLParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDriverPackagePackageIDVersionVersionIDBinaryURLParamsWithHTTPClient(client *http.Client) *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams {
	var ()
	return &GetDriverPackagePackageIDVersionVersionIDBinaryURLParams{
		HTTPClient: client,
	}
}

/*GetDriverPackagePackageIDVersionVersionIDBinaryURLParams contains all the parameters to send to the API endpoint
for the get driver package package ID version version ID binary URL operation typically these are written to a http.Request
*/
type GetDriverPackagePackageIDVersionVersionIDBinaryURLParams struct {

	/*PackageID*/
	PackageID string
	/*VersionID*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get driver package package ID version version ID binary URL params
func (o *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams) WithTimeout(timeout time.Duration) *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get driver package package ID version version ID binary URL params
func (o *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get driver package package ID version version ID binary URL params
func (o *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams) WithContext(ctx context.Context) *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get driver package package ID version version ID binary URL params
func (o *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get driver package package ID version version ID binary URL params
func (o *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams) WithHTTPClient(client *http.Client) *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get driver package package ID version version ID binary URL params
func (o *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPackageID adds the packageID to the get driver package package ID version version ID binary URL params
func (o *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams) WithPackageID(packageID string) *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams {
	o.SetPackageID(packageID)
	return o
}

// SetPackageID adds the packageId to the get driver package package ID version version ID binary URL params
func (o *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams) SetPackageID(packageID string) {
	o.PackageID = packageID
}

// WithVersionID adds the versionID to the get driver package package ID version version ID binary URL params
func (o *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams) WithVersionID(versionID string) *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the get driver package package ID version version ID binary URL params
func (o *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDriverPackagePackageIDVersionVersionIDBinaryURLParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param packageId
	if err := r.SetPathParam("packageId", o.PackageID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
