// Code generated by go-swagger; DO NOT EDIT.

package software_package

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSoftwarePackagePackageIDParams creates a new DeleteSoftwarePackagePackageIDParams object
// with the default values initialized.
func NewDeleteSoftwarePackagePackageIDParams() *DeleteSoftwarePackagePackageIDParams {
	var ()
	return &DeleteSoftwarePackagePackageIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSoftwarePackagePackageIDParamsWithTimeout creates a new DeleteSoftwarePackagePackageIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSoftwarePackagePackageIDParamsWithTimeout(timeout time.Duration) *DeleteSoftwarePackagePackageIDParams {
	var ()
	return &DeleteSoftwarePackagePackageIDParams{

		timeout: timeout,
	}
}

// NewDeleteSoftwarePackagePackageIDParamsWithContext creates a new DeleteSoftwarePackagePackageIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSoftwarePackagePackageIDParamsWithContext(ctx context.Context) *DeleteSoftwarePackagePackageIDParams {
	var ()
	return &DeleteSoftwarePackagePackageIDParams{

		Context: ctx,
	}
}

// NewDeleteSoftwarePackagePackageIDParamsWithHTTPClient creates a new DeleteSoftwarePackagePackageIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSoftwarePackagePackageIDParamsWithHTTPClient(client *http.Client) *DeleteSoftwarePackagePackageIDParams {
	var ()
	return &DeleteSoftwarePackagePackageIDParams{
		HTTPClient: client,
	}
}

/*DeleteSoftwarePackagePackageIDParams contains all the parameters to send to the API endpoint
for the delete software package package ID operation typically these are written to a http.Request
*/
type DeleteSoftwarePackagePackageIDParams struct {

	/*PackageID*/
	PackageID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete software package package ID params
func (o *DeleteSoftwarePackagePackageIDParams) WithTimeout(timeout time.Duration) *DeleteSoftwarePackagePackageIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete software package package ID params
func (o *DeleteSoftwarePackagePackageIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete software package package ID params
func (o *DeleteSoftwarePackagePackageIDParams) WithContext(ctx context.Context) *DeleteSoftwarePackagePackageIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete software package package ID params
func (o *DeleteSoftwarePackagePackageIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete software package package ID params
func (o *DeleteSoftwarePackagePackageIDParams) WithHTTPClient(client *http.Client) *DeleteSoftwarePackagePackageIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete software package package ID params
func (o *DeleteSoftwarePackagePackageIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPackageID adds the packageID to the delete software package package ID params
func (o *DeleteSoftwarePackagePackageIDParams) WithPackageID(packageID string) *DeleteSoftwarePackagePackageIDParams {
	o.SetPackageID(packageID)
	return o
}

// SetPackageID adds the packageId to the delete software package package ID params
func (o *DeleteSoftwarePackagePackageIDParams) SetPackageID(packageID string) {
	o.PackageID = packageID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSoftwarePackagePackageIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param packageId
	if err := r.SetPathParam("packageId", o.PackageID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
