// Code generated by go-swagger; DO NOT EDIT.

package software_package

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSoftwarePackageParams creates a new GetSoftwarePackageParams object
// with the default values initialized.
func NewGetSoftwarePackageParams() *GetSoftwarePackageParams {
	var ()
	return &GetSoftwarePackageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSoftwarePackageParamsWithTimeout creates a new GetSoftwarePackageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSoftwarePackageParamsWithTimeout(timeout time.Duration) *GetSoftwarePackageParams {
	var ()
	return &GetSoftwarePackageParams{

		timeout: timeout,
	}
}

// NewGetSoftwarePackageParamsWithContext creates a new GetSoftwarePackageParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSoftwarePackageParamsWithContext(ctx context.Context) *GetSoftwarePackageParams {
	var ()
	return &GetSoftwarePackageParams{

		Context: ctx,
	}
}

// NewGetSoftwarePackageParamsWithHTTPClient creates a new GetSoftwarePackageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSoftwarePackageParamsWithHTTPClient(client *http.Client) *GetSoftwarePackageParams {
	var ()
	return &GetSoftwarePackageParams{
		HTTPClient: client,
	}
}

/*GetSoftwarePackageParams contains all the parameters to send to the API endpoint
for the get software package operation typically these are written to a http.Request
*/
type GetSoftwarePackageParams struct {

	/*NextToken*/
	NextToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get software package params
func (o *GetSoftwarePackageParams) WithTimeout(timeout time.Duration) *GetSoftwarePackageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get software package params
func (o *GetSoftwarePackageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get software package params
func (o *GetSoftwarePackageParams) WithContext(ctx context.Context) *GetSoftwarePackageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get software package params
func (o *GetSoftwarePackageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get software package params
func (o *GetSoftwarePackageParams) WithHTTPClient(client *http.Client) *GetSoftwarePackageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get software package params
func (o *GetSoftwarePackageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNextToken adds the nextToken to the get software package params
func (o *GetSoftwarePackageParams) WithNextToken(nextToken *string) *GetSoftwarePackageParams {
	o.SetNextToken(nextToken)
	return o
}

// SetNextToken adds the nextToken to the get software package params
func (o *GetSoftwarePackageParams) SetNextToken(nextToken *string) {
	o.NextToken = nextToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetSoftwarePackageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.NextToken != nil {

		// query param nextToken
		var qrNextToken string
		if o.NextToken != nil {
			qrNextToken = *o.NextToken
		}
		qNextToken := qrNextToken
		if qNextToken != "" {
			if err := r.SetQueryParam("nextToken", qNextToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
