// Code generated by go-swagger; DO NOT EDIT.

package software_package

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// NewPostSoftwarePackageParams creates a new PostSoftwarePackageParams object
// with the default values initialized.
func NewPostSoftwarePackageParams() *PostSoftwarePackageParams {
	var ()
	return &PostSoftwarePackageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSoftwarePackageParamsWithTimeout creates a new PostSoftwarePackageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSoftwarePackageParamsWithTimeout(timeout time.Duration) *PostSoftwarePackageParams {
	var ()
	return &PostSoftwarePackageParams{

		timeout: timeout,
	}
}

// NewPostSoftwarePackageParamsWithContext creates a new PostSoftwarePackageParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSoftwarePackageParamsWithContext(ctx context.Context) *PostSoftwarePackageParams {
	var ()
	return &PostSoftwarePackageParams{

		Context: ctx,
	}
}

// NewPostSoftwarePackageParamsWithHTTPClient creates a new PostSoftwarePackageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSoftwarePackageParamsWithHTTPClient(client *http.Client) *PostSoftwarePackageParams {
	var ()
	return &PostSoftwarePackageParams{
		HTTPClient: client,
	}
}

/*PostSoftwarePackageParams contains all the parameters to send to the API endpoint
for the post software package operation typically these are written to a http.Request
*/
type PostSoftwarePackageParams struct {

	/*Body*/
	Body *models.CreateSoftwarePackage

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post software package params
func (o *PostSoftwarePackageParams) WithTimeout(timeout time.Duration) *PostSoftwarePackageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post software package params
func (o *PostSoftwarePackageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post software package params
func (o *PostSoftwarePackageParams) WithContext(ctx context.Context) *PostSoftwarePackageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post software package params
func (o *PostSoftwarePackageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post software package params
func (o *PostSoftwarePackageParams) WithHTTPClient(client *http.Client) *PostSoftwarePackageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post software package params
func (o *PostSoftwarePackageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post software package params
func (o *PostSoftwarePackageParams) WithBody(body *models.CreateSoftwarePackage) *PostSoftwarePackageParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post software package params
func (o *PostSoftwarePackageParams) SetBody(body *models.CreateSoftwarePackage) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostSoftwarePackageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
