// Code generated by go-swagger; DO NOT EDIT.

package fleet_workstation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams object
// with the default values initialized.
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams() *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithTimeout creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams{

		timeout: timeout,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithContext creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithContext(ctx context.Context) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams{

		Context: ctx,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithHTTPClient creates a new DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams{
		HTTPClient: client,
	}
}

/*DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams contains all the parameters to send to the API endpoint
for the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile operation typically these are written to a http.Request
*/
type DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams struct {

	/*Body*/
	Body *models.UnlinkFleetWorkstation2FleetSoftwareProfile
	/*BrandID*/
	BrandID string
	/*CountryID*/
	CountryID string
	/*StoreID*/
	StoreID string
	/*TenantID*/
	TenantID string
	/*WorkstationID*/
	WorkstationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithContext(ctx context.Context) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithBody(body *models.UnlinkFleetWorkstation2FleetSoftwareProfile) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetBody(body *models.UnlinkFleetWorkstation2FleetSoftwareProfile) {
	o.Body = body
}

// WithBrandID adds the brandID to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithBrandID(brandID string) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithCountryID adds the countryID to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithCountryID(countryID string) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetCountryID(countryID)
	return o
}

// SetCountryID adds the countryId to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetCountryID(countryID string) {
	o.CountryID = countryID
}

// WithStoreID adds the storeID to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithStoreID(storeID string) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetStoreID(storeID)
	return o
}

// SetStoreID adds the storeId to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetStoreID(storeID string) {
	o.StoreID = storeID
}

// WithTenantID adds the tenantID to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithTenantID(tenantID string) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WithWorkstationID adds the workstationID to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithWorkstationID(workstationID string) *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetWorkstationID(workstationID)
	return o
}

// SetWorkstationID adds the workstationId to the delete fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetWorkstationID(workstationID string) {
	o.WorkstationID = workstationID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param countryId
	if err := r.SetPathParam("countryId", o.CountryID); err != nil {
		return err
	}

	// path param storeId
	if err := r.SetPathParam("storeId", o.StoreID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	// path param workstationId
	if err := r.SetPathParam("workstationId", o.WorkstationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
