// Code generated by go-swagger; DO NOT EDIT.

package fleet_workstation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams creates a new GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams object
// with the default values initialized.
func NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams() *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParamsWithTimeout creates a new GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParamsWithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams{

		timeout: timeout,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParamsWithContext creates a new GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParamsWithContext(ctx context.Context) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams{

		Context: ctx,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParamsWithHTTPClient creates a new GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParamsWithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams{
		HTTPClient: client,
	}
}

/*GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams contains all the parameters to send to the API endpoint
for the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation operation typically these are written to a http.Request
*/
type GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams struct {

	/*BrandID*/
	BrandID string
	/*CountryID*/
	CountryID string
	/*NextToken*/
	NextToken *string
	/*StoreID*/
	StoreID string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) WithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) WithContext(ctx context.Context) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) WithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBrandID adds the brandID to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) WithBrandID(brandID string) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithCountryID adds the countryID to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) WithCountryID(countryID string) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	o.SetCountryID(countryID)
	return o
}

// SetCountryID adds the countryId to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) SetCountryID(countryID string) {
	o.CountryID = countryID
}

// WithNextToken adds the nextToken to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) WithNextToken(nextToken *string) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	o.SetNextToken(nextToken)
	return o
}

// SetNextToken adds the nextToken to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) SetNextToken(nextToken *string) {
	o.NextToken = nextToken
}

// WithStoreID adds the storeID to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) WithStoreID(storeID string) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	o.SetStoreID(storeID)
	return o
}

// SetStoreID adds the storeId to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) SetStoreID(storeID string) {
	o.StoreID = storeID
}

// WithTenantID adds the tenantID to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) WithTenantID(tenantID string) *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get fleet tenant tenant ID brand brand ID country country ID store store ID workstation params
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param countryId
	if err := r.SetPathParam("countryId", o.CountryID); err != nil {
		return err
	}

	if o.NextToken != nil {

		// query param nextToken
		var qrNextToken string
		if o.NextToken != nil {
			qrNextToken = *o.NextToken
		}
		qNextToken := qrNextToken
		if qNextToken != "" {
			if err := r.SetQueryParam("nextToken", qNextToken); err != nil {
				return err
			}
		}

	}

	// path param storeId
	if err := r.SetPathParam("storeId", o.StoreID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
