// Code generated by go-swagger; DO NOT EDIT.

package fleet_workstation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// NewPostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams creates a new PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams object
// with the default values initialized.
func NewPostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams() *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithTimeout creates a new PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithTimeout(timeout time.Duration) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams{

		timeout: timeout,
	}
}

// NewPostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithContext creates a new PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithContext(ctx context.Context) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams{

		Context: ctx,
	}
}

// NewPostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithHTTPClient creates a new PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParamsWithHTTPClient(client *http.Client) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams{
		HTTPClient: client,
	}
}

/*PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams contains all the parameters to send to the API endpoint
for the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile operation typically these are written to a http.Request
*/
type PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams struct {

	/*Body*/
	Body *models.LinkFleetWorkstation2FleetSoftwareProfile
	/*BrandID*/
	BrandID string
	/*CountryID*/
	CountryID string
	/*StoreID*/
	StoreID string
	/*TenantID*/
	TenantID string
	/*WorkstationID*/
	WorkstationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithTimeout(timeout time.Duration) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithContext(ctx context.Context) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithHTTPClient(client *http.Client) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithBody(body *models.LinkFleetWorkstation2FleetSoftwareProfile) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetBody(body *models.LinkFleetWorkstation2FleetSoftwareProfile) {
	o.Body = body
}

// WithBrandID adds the brandID to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithBrandID(brandID string) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithCountryID adds the countryID to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithCountryID(countryID string) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetCountryID(countryID)
	return o
}

// SetCountryID adds the countryId to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetCountryID(countryID string) {
	o.CountryID = countryID
}

// WithStoreID adds the storeID to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithStoreID(storeID string) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetStoreID(storeID)
	return o
}

// SetStoreID adds the storeId to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetStoreID(storeID string) {
	o.StoreID = storeID
}

// WithTenantID adds the tenantID to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithTenantID(tenantID string) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WithWorkstationID adds the workstationID to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WithWorkstationID(workstationID string) *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams {
	o.SetWorkstationID(workstationID)
	return o
}

// SetWorkstationID adds the workstationId to the post fleet tenant tenant ID brand brand ID country country ID store store ID workstation workstation ID fleetsoftwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) SetWorkstationID(workstationID string) {
	o.WorkstationID = workstationID
}

// WriteToRequest writes these params to a swagger request
func (o *PostFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDWorkstationWorkstationIDFleetsoftwareprofileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param countryId
	if err := r.SetPathParam("countryId", o.CountryID); err != nil {
		return err
	}

	// path param storeId
	if err := r.SetPathParam("storeId", o.StoreID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	// path param workstationId
	if err := r.SetPathParam("workstationId", o.WorkstationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
