// Code generated by go-swagger; DO NOT EDIT.

package fleet_hardware_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLReader is a Reader for the DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURL structure.
type DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLNoContent creates a DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLNoContent with default headers values
func NewDeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLNoContent() *DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLNoContent {
	return &DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLNoContent{}
}

/*DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLNoContent handles this case with default header values.

No Content
*/
type DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLNoContent struct {
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLNoContent) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/brand/{brandId}/hardwareprofile/{hardwareProfileId}/jposPathsPropertiesUrl][%d] deleteFleetTenantTenantIdBrandBrandIdHardwareprofileHardwareProfileIdJposPathsPropertiesUrlNoContent ", 204)
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLBadRequest creates a DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLBadRequest with default headers values
func NewDeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLBadRequest() *DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLBadRequest {
	return &DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLBadRequest{}
}

/*DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLBadRequest handles this case with default header values.

Bad Request
*/
type DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLBadRequest struct {
	Payload *models.Error
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/brand/{brandId}/hardwareprofile/{hardwareProfileId}/jposPathsPropertiesUrl][%d] deleteFleetTenantTenantIdBrandBrandIdHardwareprofileHardwareProfileIdJposPathsPropertiesUrlBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
