// Code generated by go-swagger; DO NOT EDIT.

package fleet_hardware_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams creates a new GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams object
// with the default values initialized.
func NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams() *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParamsWithTimeout creates a new GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParamsWithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams{

		timeout: timeout,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParamsWithContext creates a new GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParamsWithContext(ctx context.Context) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams{

		Context: ctx,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParamsWithHTTPClient creates a new GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParamsWithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams{
		HTTPClient: client,
	}
}

/*GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams contains all the parameters to send to the API endpoint
for the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml operation typically these are written to a http.Request
*/
type GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams struct {

	/*BrandID*/
	BrandID string
	/*HardwareProfileID*/
	HardwareProfileID string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) WithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) WithContext(ctx context.Context) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) WithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBrandID adds the brandID to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) WithBrandID(brandID string) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithHardwareProfileID adds the hardwareProfileID to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) WithHardwareProfileID(hardwareProfileID string) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams {
	o.SetHardwareProfileID(hardwareProfileID)
	return o
}

// SetHardwareProfileID adds the hardwareProfileId to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) SetHardwareProfileID(hardwareProfileID string) {
	o.HardwareProfileID = hardwareProfileID
}

// WithTenantID adds the tenantID to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) WithTenantID(tenantID string) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jposentriesxml params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposentriesxmlParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param hardwareProfileId
	if err := r.SetPathParam("hardwareProfileId", o.HardwareProfileID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
