// Code generated by go-swagger; DO NOT EDIT.

package fleet_hardware_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams creates a new GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams object
// with the default values initialized.
func NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams() *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParamsWithTimeout creates a new GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParamsWithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams{

		timeout: timeout,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParamsWithContext creates a new GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParamsWithContext(ctx context.Context) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams{

		Context: ctx,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParamsWithHTTPClient creates a new GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParamsWithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams{
		HTTPClient: client,
	}
}

/*GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams contains all the parameters to send to the API endpoint
for the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL operation typically these are written to a http.Request
*/
type GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams struct {

	/*BrandID*/
	BrandID string
	/*HardwareProfileID*/
	HardwareProfileID string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) WithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) WithContext(ctx context.Context) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) WithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBrandID adds the brandID to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) WithBrandID(brandID string) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithHardwareProfileID adds the hardwareProfileID to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) WithHardwareProfileID(hardwareProfileID string) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams {
	o.SetHardwareProfileID(hardwareProfileID)
	return o
}

// SetHardwareProfileID adds the hardwareProfileId to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) SetHardwareProfileID(hardwareProfileID string) {
	o.HardwareProfileID = hardwareProfileID
}

// WithTenantID adds the tenantID to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) WithTenantID(tenantID string) *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID jpos paths properties URL params
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDJposPathsPropertiesURLParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param hardwareProfileId
	if err := r.SetPathParam("hardwareProfileId", o.HardwareProfileID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
