// Code generated by go-swagger; DO NOT EDIT.

package fleet_hardware_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileParams creates a new PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams object
// with the default values initialized.
func NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileParams() *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileParamsWithTimeout creates a new PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileParamsWithTimeout(timeout time.Duration) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams{

		timeout: timeout,
	}
}

// NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileParamsWithContext creates a new PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileParamsWithContext(ctx context.Context) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams{

		Context: ctx,
	}
}

// NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileParamsWithHTTPClient creates a new PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileParamsWithHTTPClient(client *http.Client) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams{
		HTTPClient: client,
	}
}

/*PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams contains all the parameters to send to the API endpoint
for the post fleet tenant tenant ID brand brand ID hardwareprofile operation typically these are written to a http.Request
*/
type PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams struct {

	/*Body*/
	Body *models.CreateFleetHardwareProfile
	/*BrandID*/
	BrandID string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) WithTimeout(timeout time.Duration) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) WithContext(ctx context.Context) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) WithHTTPClient(client *http.Client) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) WithBody(body *models.CreateFleetHardwareProfile) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) SetBody(body *models.CreateFleetHardwareProfile) {
	o.Body = body
}

// WithBrandID adds the brandID to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) WithBrandID(brandID string) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithTenantID adds the tenantID to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) WithTenantID(tenantID string) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the post fleet tenant tenant ID brand brand ID hardwareprofile params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
