// Code generated by go-swagger; DO NOT EDIT.

package fleet_hardware_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams creates a new PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams object
// with the default values initialized.
func NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams() *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParamsWithTimeout creates a new PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParamsWithTimeout(timeout time.Duration) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams{

		timeout: timeout,
	}
}

// NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParamsWithContext creates a new PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParamsWithContext(ctx context.Context) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams{

		Context: ctx,
	}
}

// NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParamsWithHTTPClient creates a new PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParamsWithHTTPClient(client *http.Client) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams {
	var ()
	return &PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams{
		HTTPClient: client,
	}
}

/*PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams contains all the parameters to send to the API endpoint
for the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID operation typically these are written to a http.Request
*/
type PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams struct {

	/*Body*/
	Body *models.FleetHardwareProfile2InventoryModel
	/*BrandID*/
	BrandID string
	/*HardwareProfileID*/
	HardwareProfileID string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) WithTimeout(timeout time.Duration) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) WithContext(ctx context.Context) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) WithHTTPClient(client *http.Client) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) WithBody(body *models.FleetHardwareProfile2InventoryModel) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) SetBody(body *models.FleetHardwareProfile2InventoryModel) {
	o.Body = body
}

// WithBrandID adds the brandID to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) WithBrandID(brandID string) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithHardwareProfileID adds the hardwareProfileID to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) WithHardwareProfileID(hardwareProfileID string) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams {
	o.SetHardwareProfileID(hardwareProfileID)
	return o
}

// SetHardwareProfileID adds the hardwareProfileId to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) SetHardwareProfileID(hardwareProfileID string) {
	o.HardwareProfileID = hardwareProfileID
}

// WithTenantID adds the tenantID to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) WithTenantID(tenantID string) *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the post fleet tenant tenant ID brand brand ID hardwareprofile hardware profile ID params
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param hardwareProfileId
	if err := r.SetPathParam("hardwareProfileId", o.HardwareProfileID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
