// Code generated by go-swagger; DO NOT EDIT.

package fleet_hardware_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDReader is a Reader for the PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileID structure.
type PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNoContent creates a PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNoContent with default headers values
func NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNoContent() *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNoContent {
	return &PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNoContent{}
}

/*PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNoContent handles this case with default header values.

No Content
*/
type PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNoContent struct {
}

func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNoContent) Error() string {
	return fmt.Sprintf("[POST /fleet/tenant/{tenantId}/brand/{brandId}/hardwareprofile/{hardwareProfileId}][%d] postFleetTenantTenantIdBrandBrandIdHardwareprofileHardwareProfileIdNoContent ", 204)
}

func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDBadRequest creates a PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDBadRequest with default headers values
func NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDBadRequest() *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDBadRequest {
	return &PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDBadRequest{}
}

/*PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDBadRequest handles this case with default header values.

Bad Request
*/
type PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDBadRequest struct {
	Payload *models.Error
}

func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDBadRequest) Error() string {
	return fmt.Sprintf("[POST /fleet/tenant/{tenantId}/brand/{brandId}/hardwareprofile/{hardwareProfileId}][%d] postFleetTenantTenantIdBrandBrandIdHardwareprofileHardwareProfileIdBadRequest  %+v", 400, o.Payload)
}

func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNotFound creates a PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNotFound with default headers values
func NewPostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNotFound() *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNotFound {
	return &PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNotFound{}
}

/*PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNotFound handles this case with default header values.

Not Found
*/
type PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNotFound struct {
}

func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNotFound) Error() string {
	return fmt.Sprintf("[POST /fleet/tenant/{tenantId}/brand/{brandId}/hardwareprofile/{hardwareProfileId}][%d] postFleetTenantTenantIdBrandBrandIdHardwareprofileHardwareProfileIdNotFound ", 404)
}

func (o *PostFleetTenantTenantIDBrandBrandIDHardwareprofileHardwareProfileIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
