// Code generated by go-swagger; DO NOT EDIT.

package fleet_store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesReader is a Reader for the DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemproperties structure.
type DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesNoContent creates a DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesNoContent with default headers values
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesNoContent() *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesNoContent {
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesNoContent{}
}

/*DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesNoContent handles this case with default header values.

No Content
*/
type DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesNoContent struct {
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesNoContent) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/brand/{brandId}/country/{countryId}/store/{storeId}/systemproperties][%d] deleteFleetTenantTenantIdBrandBrandIdCountryCountryIdStoreStoreIdSystempropertiesNoContent ", 204)
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesBadRequest creates a DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesBadRequest with default headers values
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesBadRequest() *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesBadRequest {
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesBadRequest{}
}

/*DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesBadRequest handles this case with default header values.

Bad Request
*/
type DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesBadRequest struct {
	Payload *models.Error
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/brand/{brandId}/country/{countryId}/store/{storeId}/systemproperties][%d] deleteFleetTenantTenantIdBrandBrandIdCountryCountryIdStoreStoreIdSystempropertiesBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystempropertiesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
