// Code generated by go-swagger; DO NOT EDIT.

package fleet_store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLReader is a Reader for the DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURL structure.
type DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLNoContent creates a DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLNoContent with default headers values
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLNoContent() *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLNoContent {
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLNoContent{}
}

/*DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLNoContent handles this case with default header values.

No Content
*/
type DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLNoContent struct {
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLNoContent) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/brand/{brandId}/country/{countryId}/store/{storeId}/systemPropertiesUrl][%d] deleteFleetTenantTenantIdBrandBrandIdCountryCountryIdStoreStoreIdSystemPropertiesUrlNoContent ", 204)
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLBadRequest creates a DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLBadRequest with default headers values
func NewDeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLBadRequest() *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLBadRequest {
	return &DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLBadRequest{}
}

/*DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLBadRequest handles this case with default header values.

Bad Request
*/
type DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLBadRequest struct {
	Payload *models.Error
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/brand/{brandId}/country/{countryId}/store/{storeId}/systemPropertiesUrl][%d] deleteFleetTenantTenantIdBrandBrandIdCountryCountryIdStoreStoreIdSystemPropertiesUrlBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreStoreIDSystemPropertiesURLBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
