// Code generated by go-swagger; DO NOT EDIT.

package fleet_store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreReader is a Reader for the GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStore structure.
type GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreOK creates a GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreOK with default headers values
func NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreOK() *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreOK {
	return &GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreOK{}
}

/*GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreOK handles this case with default header values.

OK
*/
type GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreOK struct {
	Payload *models.FleetStores
}

func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreOK) Error() string {
	return fmt.Sprintf("[GET /fleet/tenant/{tenantId}/brand/{brandId}/country/{countryId}/store][%d] getFleetTenantTenantIdBrandBrandIdCountryCountryIdStoreOK  %+v", 200, o.Payload)
}

func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FleetStores)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreBadRequest creates a GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreBadRequest with default headers values
func NewGetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreBadRequest() *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreBadRequest {
	return &GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreBadRequest{}
}

/*GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreBadRequest handles this case with default header values.

Bad Request
*/
type GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreBadRequest struct {
	Payload *models.Error
}

func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreBadRequest) Error() string {
	return fmt.Sprintf("[GET /fleet/tenant/{tenantId}/brand/{brandId}/country/{countryId}/store][%d] getFleetTenantTenantIdBrandBrandIdCountryCountryIdStoreBadRequest  %+v", 400, o.Payload)
}

func (o *GetFleetTenantTenantIDBrandBrandIDCountryCountryIDStoreBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
