// Code generated by go-swagger; DO NOT EDIT.

package fleet_brand

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteFleetTenantTenantIDBrandBrandIDParams creates a new DeleteFleetTenantTenantIDBrandBrandIDParams object
// with the default values initialized.
func NewDeleteFleetTenantTenantIDBrandBrandIDParams() *DeleteFleetTenantTenantIDBrandBrandIDParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDParamsWithTimeout creates a new DeleteFleetTenantTenantIDBrandBrandIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFleetTenantTenantIDBrandBrandIDParamsWithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDBrandBrandIDParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDParams{

		timeout: timeout,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDParamsWithContext creates a new DeleteFleetTenantTenantIDBrandBrandIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFleetTenantTenantIDBrandBrandIDParamsWithContext(ctx context.Context) *DeleteFleetTenantTenantIDBrandBrandIDParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDParams{

		Context: ctx,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDParamsWithHTTPClient creates a new DeleteFleetTenantTenantIDBrandBrandIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFleetTenantTenantIDBrandBrandIDParamsWithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDBrandBrandIDParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDParams{
		HTTPClient: client,
	}
}

/*DeleteFleetTenantTenantIDBrandBrandIDParams contains all the parameters to send to the API endpoint
for the delete fleet tenant tenant ID brand brand ID operation typically these are written to a http.Request
*/
type DeleteFleetTenantTenantIDBrandBrandIDParams struct {

	/*BrandID*/
	BrandID string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete fleet tenant tenant ID brand brand ID params
func (o *DeleteFleetTenantTenantIDBrandBrandIDParams) WithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDBrandBrandIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete fleet tenant tenant ID brand brand ID params
func (o *DeleteFleetTenantTenantIDBrandBrandIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete fleet tenant tenant ID brand brand ID params
func (o *DeleteFleetTenantTenantIDBrandBrandIDParams) WithContext(ctx context.Context) *DeleteFleetTenantTenantIDBrandBrandIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete fleet tenant tenant ID brand brand ID params
func (o *DeleteFleetTenantTenantIDBrandBrandIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID brand brand ID params
func (o *DeleteFleetTenantTenantIDBrandBrandIDParams) WithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDBrandBrandIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID brand brand ID params
func (o *DeleteFleetTenantTenantIDBrandBrandIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBrandID adds the brandID to the delete fleet tenant tenant ID brand brand ID params
func (o *DeleteFleetTenantTenantIDBrandBrandIDParams) WithBrandID(brandID string) *DeleteFleetTenantTenantIDBrandBrandIDParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the delete fleet tenant tenant ID brand brand ID params
func (o *DeleteFleetTenantTenantIDBrandBrandIDParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithTenantID adds the tenantID to the delete fleet tenant tenant ID brand brand ID params
func (o *DeleteFleetTenantTenantIDBrandBrandIDParams) WithTenantID(tenantID string) *DeleteFleetTenantTenantIDBrandBrandIDParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the delete fleet tenant tenant ID brand brand ID params
func (o *DeleteFleetTenantTenantIDBrandBrandIDParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFleetTenantTenantIDBrandBrandIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
