// Code generated by go-swagger; DO NOT EDIT.

package fleet_brand

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesReader is a Reader for the DeleteFleetTenantTenantIDBrandBrandIDSystemproperties structure.
type DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteFleetTenantTenantIDBrandBrandIDSystempropertiesNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDSystempropertiesNoContent creates a DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesNoContent with default headers values
func NewDeleteFleetTenantTenantIDBrandBrandIDSystempropertiesNoContent() *DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesNoContent {
	return &DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesNoContent{}
}

/*DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesNoContent handles this case with default header values.

No Content
*/
type DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesNoContent struct {
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesNoContent) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/brand/{brandId}/systemproperties][%d] deleteFleetTenantTenantIdBrandBrandIdSystempropertiesNoContent ", 204)
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest creates a DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest with default headers values
func NewDeleteFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest() *DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest {
	return &DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest{}
}

/*DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest handles this case with default header values.

Bad Request
*/
type DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest struct {
	Payload *models.Error
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/brand/{brandId}/systemproperties][%d] deleteFleetTenantTenantIdBrandBrandIdSystempropertiesBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
