// Code generated by go-swagger; DO NOT EDIT.

package fleet_brand

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// GetFleetTenantTenantIDBrandBrandIDSystempropertiesReader is a Reader for the GetFleetTenantTenantIDBrandBrandIDSystemproperties structure.
type GetFleetTenantTenantIDBrandBrandIDSystempropertiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFleetTenantTenantIDBrandBrandIDSystempropertiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetFleetTenantTenantIDBrandBrandIDSystempropertiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetFleetTenantTenantIDBrandBrandIDSystempropertiesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDSystempropertiesOK creates a GetFleetTenantTenantIDBrandBrandIDSystempropertiesOK with default headers values
func NewGetFleetTenantTenantIDBrandBrandIDSystempropertiesOK() *GetFleetTenantTenantIDBrandBrandIDSystempropertiesOK {
	return &GetFleetTenantTenantIDBrandBrandIDSystempropertiesOK{}
}

/*GetFleetTenantTenantIDBrandBrandIDSystempropertiesOK handles this case with default header values.

OK
*/
type GetFleetTenantTenantIDBrandBrandIDSystempropertiesOK struct {
	Payload *models.S3PresignedPost
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystempropertiesOK) Error() string {
	return fmt.Sprintf("[GET /fleet/tenant/{tenantId}/brand/{brandId}/systemproperties][%d] getFleetTenantTenantIdBrandBrandIdSystempropertiesOK  %+v", 200, o.Payload)
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystempropertiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.S3PresignedPost)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest creates a GetFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest with default headers values
func NewGetFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest() *GetFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest {
	return &GetFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest{}
}

/*GetFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest handles this case with default header values.

Bad Request
*/
type GetFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest struct {
	Payload *models.Error
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest) Error() string {
	return fmt.Sprintf("[GET /fleet/tenant/{tenantId}/brand/{brandId}/systemproperties][%d] getFleetTenantTenantIdBrandBrandIdSystempropertiesBadRequest  %+v", 400, o.Payload)
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystempropertiesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFleetTenantTenantIDBrandBrandIDSystempropertiesNotFound creates a GetFleetTenantTenantIDBrandBrandIDSystempropertiesNotFound with default headers values
func NewGetFleetTenantTenantIDBrandBrandIDSystempropertiesNotFound() *GetFleetTenantTenantIDBrandBrandIDSystempropertiesNotFound {
	return &GetFleetTenantTenantIDBrandBrandIDSystempropertiesNotFound{}
}

/*GetFleetTenantTenantIDBrandBrandIDSystempropertiesNotFound handles this case with default header values.

Not Found
*/
type GetFleetTenantTenantIDBrandBrandIDSystempropertiesNotFound struct {
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystempropertiesNotFound) Error() string {
	return fmt.Sprintf("[GET /fleet/tenant/{tenantId}/brand/{brandId}/systemproperties][%d] getFleetTenantTenantIdBrandBrandIdSystempropertiesNotFound ", 404)
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystempropertiesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
