// Code generated by go-swagger; DO NOT EDIT.

package fleet_brand

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLReader is a Reader for the GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURL structure.
type GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLOK creates a GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLOK with default headers values
func NewGetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLOK() *GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLOK {
	return &GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLOK{}
}

/*GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLOK handles this case with default header values.

OK
*/
type GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLOK struct {
	Payload *models.S3PresignedPost
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLOK) Error() string {
	return fmt.Sprintf("[GET /fleet/tenant/{tenantId}/brand/{brandId}/systemPropertiesUrl][%d] getFleetTenantTenantIdBrandBrandIdSystemPropertiesUrlOK  %+v", 200, o.Payload)
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.S3PresignedPost)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLBadRequest creates a GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLBadRequest with default headers values
func NewGetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLBadRequest() *GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLBadRequest {
	return &GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLBadRequest{}
}

/*GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLBadRequest handles this case with default header values.

Bad Request
*/
type GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLBadRequest struct {
	Payload *models.Error
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLBadRequest) Error() string {
	return fmt.Sprintf("[GET /fleet/tenant/{tenantId}/brand/{brandId}/systemPropertiesUrl][%d] getFleetTenantTenantIdBrandBrandIdSystemPropertiesUrlBadRequest  %+v", 400, o.Payload)
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLNotFound creates a GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLNotFound with default headers values
func NewGetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLNotFound() *GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLNotFound {
	return &GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLNotFound{}
}

/*GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLNotFound handles this case with default header values.

Not Found
*/
type GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLNotFound struct {
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLNotFound) Error() string {
	return fmt.Sprintf("[GET /fleet/tenant/{tenantId}/brand/{brandId}/systemPropertiesUrl][%d] getFleetTenantTenantIdBrandBrandIdSystemPropertiesUrlNotFound ", 404)
}

func (o *GetFleetTenantTenantIDBrandBrandIDSystemPropertiesURLNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
