// Code generated by go-swagger; DO NOT EDIT.

package fleet_brand

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFleetTenantTenantIDBrandParams creates a new GetFleetTenantTenantIDBrandParams object
// with the default values initialized.
func NewGetFleetTenantTenantIDBrandParams() *GetFleetTenantTenantIDBrandParams {
	var ()
	return &GetFleetTenantTenantIDBrandParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFleetTenantTenantIDBrandParamsWithTimeout creates a new GetFleetTenantTenantIDBrandParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFleetTenantTenantIDBrandParamsWithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandParams {
	var ()
	return &GetFleetTenantTenantIDBrandParams{

		timeout: timeout,
	}
}

// NewGetFleetTenantTenantIDBrandParamsWithContext creates a new GetFleetTenantTenantIDBrandParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFleetTenantTenantIDBrandParamsWithContext(ctx context.Context) *GetFleetTenantTenantIDBrandParams {
	var ()
	return &GetFleetTenantTenantIDBrandParams{

		Context: ctx,
	}
}

// NewGetFleetTenantTenantIDBrandParamsWithHTTPClient creates a new GetFleetTenantTenantIDBrandParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFleetTenantTenantIDBrandParamsWithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandParams {
	var ()
	return &GetFleetTenantTenantIDBrandParams{
		HTTPClient: client,
	}
}

/*GetFleetTenantTenantIDBrandParams contains all the parameters to send to the API endpoint
for the get fleet tenant tenant ID brand operation typically these are written to a http.Request
*/
type GetFleetTenantTenantIDBrandParams struct {

	/*NextToken*/
	NextToken *string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get fleet tenant tenant ID brand params
func (o *GetFleetTenantTenantIDBrandParams) WithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fleet tenant tenant ID brand params
func (o *GetFleetTenantTenantIDBrandParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fleet tenant tenant ID brand params
func (o *GetFleetTenantTenantIDBrandParams) WithContext(ctx context.Context) *GetFleetTenantTenantIDBrandParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fleet tenant tenant ID brand params
func (o *GetFleetTenantTenantIDBrandParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand params
func (o *GetFleetTenantTenantIDBrandParams) WithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand params
func (o *GetFleetTenantTenantIDBrandParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNextToken adds the nextToken to the get fleet tenant tenant ID brand params
func (o *GetFleetTenantTenantIDBrandParams) WithNextToken(nextToken *string) *GetFleetTenantTenantIDBrandParams {
	o.SetNextToken(nextToken)
	return o
}

// SetNextToken adds the nextToken to the get fleet tenant tenant ID brand params
func (o *GetFleetTenantTenantIDBrandParams) SetNextToken(nextToken *string) {
	o.NextToken = nextToken
}

// WithTenantID adds the tenantID to the get fleet tenant tenant ID brand params
func (o *GetFleetTenantTenantIDBrandParams) WithTenantID(tenantID string) *GetFleetTenantTenantIDBrandParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get fleet tenant tenant ID brand params
func (o *GetFleetTenantTenantIDBrandParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFleetTenantTenantIDBrandParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.NextToken != nil {

		// query param nextToken
		var qrNextToken string
		if o.NextToken != nil {
			qrNextToken = *o.NextToken
		}
		qNextToken := qrNextToken
		if qNextToken != "" {
			if err := r.SetQueryParam("nextToken", qNextToken); err != nil {
				return err
			}
		}

	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
