// Code generated by go-swagger; DO NOT EDIT.

package fleet_brand

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// PutFleetTenantTenantIDBrandBrandIDReader is a Reader for the PutFleetTenantTenantIDBrandBrandID structure.
type PutFleetTenantTenantIDBrandBrandIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutFleetTenantTenantIDBrandBrandIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutFleetTenantTenantIDBrandBrandIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutFleetTenantTenantIDBrandBrandIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutFleetTenantTenantIDBrandBrandIDNoContent creates a PutFleetTenantTenantIDBrandBrandIDNoContent with default headers values
func NewPutFleetTenantTenantIDBrandBrandIDNoContent() *PutFleetTenantTenantIDBrandBrandIDNoContent {
	return &PutFleetTenantTenantIDBrandBrandIDNoContent{}
}

/*PutFleetTenantTenantIDBrandBrandIDNoContent handles this case with default header values.

No Content
*/
type PutFleetTenantTenantIDBrandBrandIDNoContent struct {
}

func (o *PutFleetTenantTenantIDBrandBrandIDNoContent) Error() string {
	return fmt.Sprintf("[PUT /fleet/tenant/{tenantId}/brand/{brandId}][%d] putFleetTenantTenantIdBrandBrandIdNoContent ", 204)
}

func (o *PutFleetTenantTenantIDBrandBrandIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutFleetTenantTenantIDBrandBrandIDBadRequest creates a PutFleetTenantTenantIDBrandBrandIDBadRequest with default headers values
func NewPutFleetTenantTenantIDBrandBrandIDBadRequest() *PutFleetTenantTenantIDBrandBrandIDBadRequest {
	return &PutFleetTenantTenantIDBrandBrandIDBadRequest{}
}

/*PutFleetTenantTenantIDBrandBrandIDBadRequest handles this case with default header values.

Bad Request
*/
type PutFleetTenantTenantIDBrandBrandIDBadRequest struct {
	Payload *models.Error
}

func (o *PutFleetTenantTenantIDBrandBrandIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /fleet/tenant/{tenantId}/brand/{brandId}][%d] putFleetTenantTenantIdBrandBrandIdBadRequest  %+v", 400, o.Payload)
}

func (o *PutFleetTenantTenantIDBrandBrandIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
