// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FleetHardwareProfile2InventoryModel fleet hardware profile2 inventory model
// swagger:model FleetHardwareProfile2InventoryModel
type FleetHardwareProfile2InventoryModel struct {

	// layer
	// Required: true
	// Enum: [cashchanger cashdrawer eft fiscal linedisplay msr printer printer2 scale scanner scanner2]
	Layer *string `json:"layer"`

	// model
	// Required: true
	Model *FleetHardwareProfile2InventoryModelModel `json:"model"`

	// port
	// Required: true
	// Enum: [usb com1 com2 com3 com4 com5 com6 com7 com8 com9]
	Port *string `json:"port"`
}

// Validate validates this fleet hardware profile2 inventory model
func (m *FleetHardwareProfile2InventoryModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLayer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePort(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var fleetHardwareProfile2InventoryModelTypeLayerPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["cashchanger","cashdrawer","eft","fiscal","linedisplay","msr","printer","printer2","scale","scanner","scanner2"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		fleetHardwareProfile2InventoryModelTypeLayerPropEnum = append(fleetHardwareProfile2InventoryModelTypeLayerPropEnum, v)
	}
}

const (

	// FleetHardwareProfile2InventoryModelLayerCashchanger captures enum value "cashchanger"
	FleetHardwareProfile2InventoryModelLayerCashchanger string = "cashchanger"

	// FleetHardwareProfile2InventoryModelLayerCashdrawer captures enum value "cashdrawer"
	FleetHardwareProfile2InventoryModelLayerCashdrawer string = "cashdrawer"

	// FleetHardwareProfile2InventoryModelLayerEft captures enum value "eft"
	FleetHardwareProfile2InventoryModelLayerEft string = "eft"

	// FleetHardwareProfile2InventoryModelLayerFiscal captures enum value "fiscal"
	FleetHardwareProfile2InventoryModelLayerFiscal string = "fiscal"

	// FleetHardwareProfile2InventoryModelLayerLinedisplay captures enum value "linedisplay"
	FleetHardwareProfile2InventoryModelLayerLinedisplay string = "linedisplay"

	// FleetHardwareProfile2InventoryModelLayerMsr captures enum value "msr"
	FleetHardwareProfile2InventoryModelLayerMsr string = "msr"

	// FleetHardwareProfile2InventoryModelLayerPrinter captures enum value "printer"
	FleetHardwareProfile2InventoryModelLayerPrinter string = "printer"

	// FleetHardwareProfile2InventoryModelLayerPrinter2 captures enum value "printer2"
	FleetHardwareProfile2InventoryModelLayerPrinter2 string = "printer2"

	// FleetHardwareProfile2InventoryModelLayerScale captures enum value "scale"
	FleetHardwareProfile2InventoryModelLayerScale string = "scale"

	// FleetHardwareProfile2InventoryModelLayerScanner captures enum value "scanner"
	FleetHardwareProfile2InventoryModelLayerScanner string = "scanner"

	// FleetHardwareProfile2InventoryModelLayerScanner2 captures enum value "scanner2"
	FleetHardwareProfile2InventoryModelLayerScanner2 string = "scanner2"
)

// prop value enum
func (m *FleetHardwareProfile2InventoryModel) validateLayerEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, fleetHardwareProfile2InventoryModelTypeLayerPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *FleetHardwareProfile2InventoryModel) validateLayer(formats strfmt.Registry) error {

	if err := validate.Required("layer", "body", m.Layer); err != nil {
		return err
	}

	// value enum
	if err := m.validateLayerEnum("layer", "body", *m.Layer); err != nil {
		return err
	}

	return nil
}

func (m *FleetHardwareProfile2InventoryModel) validateModel(formats strfmt.Registry) error {

	if err := validate.Required("model", "body", m.Model); err != nil {
		return err
	}

	if m.Model != nil {
		if err := m.Model.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("model")
			}
			return err
		}
	}

	return nil
}

var fleetHardwareProfile2InventoryModelTypePortPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["usb","com1","com2","com3","com4","com5","com6","com7","com8","com9"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		fleetHardwareProfile2InventoryModelTypePortPropEnum = append(fleetHardwareProfile2InventoryModelTypePortPropEnum, v)
	}
}

const (

	// FleetHardwareProfile2InventoryModelPortUsb captures enum value "usb"
	FleetHardwareProfile2InventoryModelPortUsb string = "usb"

	// FleetHardwareProfile2InventoryModelPortCom1 captures enum value "com1"
	FleetHardwareProfile2InventoryModelPortCom1 string = "com1"

	// FleetHardwareProfile2InventoryModelPortCom2 captures enum value "com2"
	FleetHardwareProfile2InventoryModelPortCom2 string = "com2"

	// FleetHardwareProfile2InventoryModelPortCom3 captures enum value "com3"
	FleetHardwareProfile2InventoryModelPortCom3 string = "com3"

	// FleetHardwareProfile2InventoryModelPortCom4 captures enum value "com4"
	FleetHardwareProfile2InventoryModelPortCom4 string = "com4"

	// FleetHardwareProfile2InventoryModelPortCom5 captures enum value "com5"
	FleetHardwareProfile2InventoryModelPortCom5 string = "com5"

	// FleetHardwareProfile2InventoryModelPortCom6 captures enum value "com6"
	FleetHardwareProfile2InventoryModelPortCom6 string = "com6"

	// FleetHardwareProfile2InventoryModelPortCom7 captures enum value "com7"
	FleetHardwareProfile2InventoryModelPortCom7 string = "com7"

	// FleetHardwareProfile2InventoryModelPortCom8 captures enum value "com8"
	FleetHardwareProfile2InventoryModelPortCom8 string = "com8"

	// FleetHardwareProfile2InventoryModelPortCom9 captures enum value "com9"
	FleetHardwareProfile2InventoryModelPortCom9 string = "com9"
)

// prop value enum
func (m *FleetHardwareProfile2InventoryModel) validatePortEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, fleetHardwareProfile2InventoryModelTypePortPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *FleetHardwareProfile2InventoryModel) validatePort(formats strfmt.Registry) error {

	if err := validate.Required("port", "body", m.Port); err != nil {
		return err
	}

	// value enum
	if err := m.validatePortEnum("port", "body", *m.Port); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FleetHardwareProfile2InventoryModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FleetHardwareProfile2InventoryModel) UnmarshalBinary(b []byte) error {
	var res FleetHardwareProfile2InventoryModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// FleetHardwareProfile2InventoryModelModel fleet hardware profile2 inventory model model
// swagger:model FleetHardwareProfile2InventoryModelModel
type FleetHardwareProfile2InventoryModelModel struct {

	// manufacturer Id
	// Required: true
	ManufacturerID *string `json:"manufacturerId"`

	// model Id
	// Required: true
	ModelID *string `json:"modelId"`
}

// Validate validates this fleet hardware profile2 inventory model model
func (m *FleetHardwareProfile2InventoryModelModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateManufacturerID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateModelID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FleetHardwareProfile2InventoryModelModel) validateManufacturerID(formats strfmt.Registry) error {

	if err := validate.Required("model"+"."+"manufacturerId", "body", m.ManufacturerID); err != nil {
		return err
	}

	return nil
}

func (m *FleetHardwareProfile2InventoryModelModel) validateModelID(formats strfmt.Registry) error {

	if err := validate.Required("model"+"."+"modelId", "body", m.ModelID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FleetHardwareProfile2InventoryModelModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FleetHardwareProfile2InventoryModelModel) UnmarshalBinary(b []byte) error {
	var res FleetHardwareProfile2InventoryModelModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
