// Code generated by go-swagger; DO NOT EDIT.

package fleet_software_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionReader is a Reader for the DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversion structure.
type DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNoContent creates a DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNoContent with default headers values
func NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNoContent() *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNoContent {
	return &DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNoContent{}
}

/*DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNoContent handles this case with default header values.

No Content
*/
type DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNoContent struct {
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNoContent) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/brand/{brandId}/softwareprofile/{softwareProfileId}/softwareversion][%d] deleteFleetTenantTenantIdBrandBrandIdSoftwareprofileSoftwareProfileIdSoftwareversionNoContent ", 204)
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionBadRequest creates a DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionBadRequest with default headers values
func NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionBadRequest() *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionBadRequest {
	return &DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionBadRequest{}
}

/*DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionBadRequest handles this case with default header values.

Bad Request
*/
type DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionBadRequest struct {
	Payload *models.Error
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/brand/{brandId}/softwareprofile/{softwareProfileId}/softwareversion][%d] deleteFleetTenantTenantIdBrandBrandIdSoftwareprofileSoftwareProfileIdSoftwareversionBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNotFound creates a DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNotFound with default headers values
func NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNotFound() *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNotFound {
	return &DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNotFound{}
}

/*DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNotFound handles this case with default header values.

Not Found
*/
type DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNotFound struct {
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNotFound) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/brand/{brandId}/softwareprofile/{softwareProfileId}/softwareversion][%d] deleteFleetTenantTenantIdBrandBrandIdSoftwareprofileSoftwareProfileIdSoftwareversionNotFound ", 404)
}

func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
