// Code generated by go-swagger; DO NOT EDIT.

package fleet_software_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams creates a new DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams object
// with the default values initialized.
func NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams() *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParamsWithTimeout creates a new DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParamsWithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams{

		timeout: timeout,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParamsWithContext creates a new DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParamsWithContext(ctx context.Context) *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams{

		Context: ctx,
	}
}

// NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParamsWithHTTPClient creates a new DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParamsWithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams {
	var ()
	return &DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams{
		HTTPClient: client,
	}
}

/*DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams contains all the parameters to send to the API endpoint
for the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion operation typically these are written to a http.Request
*/
type DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams struct {

	/*Body*/
	Body *models.UnlinkFleetSoftwareProfile2SoftwareVersion
	/*BrandID*/
	BrandID string
	/*SoftwareProfileID*/
	SoftwareProfileID string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) WithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) WithContext(ctx context.Context) *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) WithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) WithBody(body *models.UnlinkFleetSoftwareProfile2SoftwareVersion) *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) SetBody(body *models.UnlinkFleetSoftwareProfile2SoftwareVersion) {
	o.Body = body
}

// WithBrandID adds the brandID to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) WithBrandID(brandID string) *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithSoftwareProfileID adds the softwareProfileID to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) WithSoftwareProfileID(softwareProfileID string) *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams {
	o.SetSoftwareProfileID(softwareProfileID)
	return o
}

// SetSoftwareProfileID adds the softwareProfileId to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) SetSoftwareProfileID(softwareProfileID string) {
	o.SoftwareProfileID = softwareProfileID
}

// WithTenantID adds the tenantID to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) WithTenantID(tenantID string) *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the delete fleet tenant tenant ID brand brand ID softwareprofile software profile ID softwareversion params
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDSoftwareversionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param softwareProfileId
	if err := r.SetPathParam("softwareProfileId", o.SoftwareProfileID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
