// Code generated by go-swagger; DO NOT EDIT.

package fleet_software_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams creates a new GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams object
// with the default values initialized.
func NewGetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams() *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDSoftwareprofileParamsWithTimeout creates a new GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFleetTenantTenantIDBrandBrandIDSoftwareprofileParamsWithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams{

		timeout: timeout,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDSoftwareprofileParamsWithContext creates a new GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFleetTenantTenantIDBrandBrandIDSoftwareprofileParamsWithContext(ctx context.Context) *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams{

		Context: ctx,
	}
}

// NewGetFleetTenantTenantIDBrandBrandIDSoftwareprofileParamsWithHTTPClient creates a new GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFleetTenantTenantIDBrandBrandIDSoftwareprofileParamsWithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams {
	var ()
	return &GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams{
		HTTPClient: client,
	}
}

/*GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams contains all the parameters to send to the API endpoint
for the get fleet tenant tenant ID brand brand ID softwareprofile operation typically these are written to a http.Request
*/
type GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams struct {

	/*BrandID*/
	BrandID string
	/*NextToken*/
	NextToken *string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) WithTimeout(timeout time.Duration) *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) WithContext(ctx context.Context) *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) WithHTTPClient(client *http.Client) *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBrandID adds the brandID to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) WithBrandID(brandID string) *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithNextToken adds the nextToken to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) WithNextToken(nextToken *string) *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams {
	o.SetNextToken(nextToken)
	return o
}

// SetNextToken adds the nextToken to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) SetNextToken(nextToken *string) {
	o.NextToken = nextToken
}

// WithTenantID adds the tenantID to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) WithTenantID(tenantID string) *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get fleet tenant tenant ID brand brand ID softwareprofile params
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFleetTenantTenantIDBrandBrandIDSoftwareprofileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	if o.NextToken != nil {

		// query param nextToken
		var qrNextToken string
		if o.NextToken != nil {
			qrNextToken = *o.NextToken
		}
		qNextToken := qrNextToken
		if qNextToken != "" {
			if err := r.SetQueryParam("nextToken", qNextToken); err != nil {
				return err
			}
		}

	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
