// Code generated by go-swagger; DO NOT EDIT.

package fleet_software_profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// NewPutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams creates a new PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams object
// with the default values initialized.
func NewPutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams() *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams {
	var ()
	return &PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParamsWithTimeout creates a new PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParamsWithTimeout(timeout time.Duration) *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams {
	var ()
	return &PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams{

		timeout: timeout,
	}
}

// NewPutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParamsWithContext creates a new PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParamsWithContext(ctx context.Context) *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams {
	var ()
	return &PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams{

		Context: ctx,
	}
}

// NewPutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParamsWithHTTPClient creates a new PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParamsWithHTTPClient(client *http.Client) *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams {
	var ()
	return &PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams{
		HTTPClient: client,
	}
}

/*PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams contains all the parameters to send to the API endpoint
for the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID operation typically these are written to a http.Request
*/
type PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams struct {

	/*Body*/
	Body *models.UpdateFleetSoftwareProfile
	/*BrandID*/
	BrandID string
	/*SoftwareProfileID*/
	SoftwareProfileID string
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) WithTimeout(timeout time.Duration) *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) WithContext(ctx context.Context) *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) WithHTTPClient(client *http.Client) *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) WithBody(body *models.UpdateFleetSoftwareProfile) *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) SetBody(body *models.UpdateFleetSoftwareProfile) {
	o.Body = body
}

// WithBrandID adds the brandID to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) WithBrandID(brandID string) *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams {
	o.SetBrandID(brandID)
	return o
}

// SetBrandID adds the brandId to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) SetBrandID(brandID string) {
	o.BrandID = brandID
}

// WithSoftwareProfileID adds the softwareProfileID to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) WithSoftwareProfileID(softwareProfileID string) *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams {
	o.SetSoftwareProfileID(softwareProfileID)
	return o
}

// SetSoftwareProfileID adds the softwareProfileId to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) SetSoftwareProfileID(softwareProfileID string) {
	o.SoftwareProfileID = softwareProfileID
}

// WithTenantID adds the tenantID to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) WithTenantID(tenantID string) *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the put fleet tenant tenant ID brand brand ID softwareprofile software profile ID params
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *PutFleetTenantTenantIDBrandBrandIDSoftwareprofileSoftwareProfileIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param brandId
	if err := r.SetPathParam("brandId", o.BrandID); err != nil {
		return err
	}

	// path param softwareProfileId
	if err := r.SetPathParam("softwareProfileId", o.SoftwareProfileID); err != nil {
		return err
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
