// Code generated by go-swagger; DO NOT EDIT.

package inventory_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlReader is a Reader for the DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxml structure.
type DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNoContent creates a DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNoContent with default headers values
func NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNoContent() *DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNoContent {
	return &DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNoContent{}
}

/*DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNoContent handles this case with default header values.

No Content
*/
type DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNoContent struct {
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNoContent) Error() string {
	return fmt.Sprintf("[DELETE /inventory/manufacturer/{manufacturerId}/model/{modelId}/jposentriesxml][%d] deleteInventoryManufacturerManufacturerIdModelModelIdJposentriesxmlNoContent ", 204)
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest creates a DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest with default headers values
func NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest() *DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest {
	return &DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest{}
}

/*DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest handles this case with default header values.

Bad Request
*/
type DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest struct {
	Payload *models.Error
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /inventory/manufacturer/{manufacturerId}/model/{modelId}/jposentriesxml][%d] deleteInventoryManufacturerManufacturerIdModelModelIdJposentriesxmlBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
