// Code generated by go-swagger; DO NOT EDIT.

package inventory_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLReader is a Reader for the DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURL structure.
type DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLNoContent creates a DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLNoContent with default headers values
func NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLNoContent() *DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLNoContent {
	return &DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLNoContent{}
}

/*DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLNoContent handles this case with default header values.

No Content
*/
type DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLNoContent struct {
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLNoContent) Error() string {
	return fmt.Sprintf("[DELETE /inventory/manufacturer/{manufacturerId}/model/{modelId}/jposEntriesXmlUrl][%d] deleteInventoryManufacturerManufacturerIdModelModelIdJposEntriesXmlUrlNoContent ", 204)
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLBadRequest creates a DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLBadRequest with default headers values
func NewDeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLBadRequest() *DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLBadRequest {
	return &DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLBadRequest{}
}

/*DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLBadRequest handles this case with default header values.

Bad Request
*/
type DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLBadRequest struct {
	Payload *models.Error
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /inventory/manufacturer/{manufacturerId}/model/{modelId}/jposEntriesXmlUrl][%d] deleteInventoryManufacturerManufacturerIdModelModelIdJposEntriesXmlUrlBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDJposEntriesXMLURLBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
