// Code generated by go-swagger; DO NOT EDIT.

package inventory_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// DeleteInventoryManufacturerManufacturerIDModelModelIDReader is a Reader for the DeleteInventoryManufacturerManufacturerIDModelModelID structure.
type DeleteInventoryManufacturerManufacturerIDModelModelIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteInventoryManufacturerManufacturerIDModelModelIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteInventoryManufacturerManufacturerIDModelModelIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteInventoryManufacturerManufacturerIDModelModelIDNoContent creates a DeleteInventoryManufacturerManufacturerIDModelModelIDNoContent with default headers values
func NewDeleteInventoryManufacturerManufacturerIDModelModelIDNoContent() *DeleteInventoryManufacturerManufacturerIDModelModelIDNoContent {
	return &DeleteInventoryManufacturerManufacturerIDModelModelIDNoContent{}
}

/*DeleteInventoryManufacturerManufacturerIDModelModelIDNoContent handles this case with default header values.

No Content
*/
type DeleteInventoryManufacturerManufacturerIDModelModelIDNoContent struct {
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /inventory/manufacturer/{manufacturerId}/model/{modelId}][%d] deleteInventoryManufacturerManufacturerIdModelModelIdNoContent ", 204)
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteInventoryManufacturerManufacturerIDModelModelIDBadRequest creates a DeleteInventoryManufacturerManufacturerIDModelModelIDBadRequest with default headers values
func NewDeleteInventoryManufacturerManufacturerIDModelModelIDBadRequest() *DeleteInventoryManufacturerManufacturerIDModelModelIDBadRequest {
	return &DeleteInventoryManufacturerManufacturerIDModelModelIDBadRequest{}
}

/*DeleteInventoryManufacturerManufacturerIDModelModelIDBadRequest handles this case with default header values.

Bad Request
*/
type DeleteInventoryManufacturerManufacturerIDModelModelIDBadRequest struct {
	Payload *models.Error
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /inventory/manufacturer/{manufacturerId}/model/{modelId}][%d] deleteInventoryManufacturerManufacturerIdModelModelIdBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteInventoryManufacturerManufacturerIDModelModelIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
