// Code generated by go-swagger; DO NOT EDIT.

package inventory_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlReader is a Reader for the GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxml structure.
type GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlOK creates a GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlOK with default headers values
func NewGetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlOK() *GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlOK {
	return &GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlOK{}
}

/*GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlOK handles this case with default header values.

OK
*/
type GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlOK struct {
	Payload *models.S3PresignedPost
}

func (o *GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlOK) Error() string {
	return fmt.Sprintf("[GET /inventory/manufacturer/{manufacturerId}/model/{modelId}/jposentriesxml][%d] getInventoryManufacturerManufacturerIdModelModelIdJposentriesxmlOK  %+v", 200, o.Payload)
}

func (o *GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.S3PresignedPost)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest creates a GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest with default headers values
func NewGetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest() *GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest {
	return &GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest{}
}

/*GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest handles this case with default header values.

Bad Request
*/
type GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest struct {
	Payload *models.Error
}

func (o *GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest) Error() string {
	return fmt.Sprintf("[GET /inventory/manufacturer/{manufacturerId}/model/{modelId}/jposentriesxml][%d] getInventoryManufacturerManufacturerIdModelModelIdJposentriesxmlBadRequest  %+v", 400, o.Payload)
}

func (o *GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNotFound creates a GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNotFound with default headers values
func NewGetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNotFound() *GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNotFound {
	return &GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNotFound{}
}

/*GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNotFound handles this case with default header values.

Not Found
*/
type GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNotFound struct {
}

func (o *GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNotFound) Error() string {
	return fmt.Sprintf("[GET /inventory/manufacturer/{manufacturerId}/model/{modelId}/jposentriesxml][%d] getInventoryManufacturerManufacturerIdModelModelIdJposentriesxmlNotFound ", 404)
}

func (o *GetInventoryManufacturerManufacturerIDModelModelIDJposentriesxmlNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
