// Code generated by go-swagger; DO NOT EDIT.

package inventory_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "fleet-manager-sdk-go/fleetmanager/models"
)

// PutInventoryManufacturerManufacturerIDModelModelIDReader is a Reader for the PutInventoryManufacturerManufacturerIDModelModelID structure.
type PutInventoryManufacturerManufacturerIDModelModelIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutInventoryManufacturerManufacturerIDModelModelIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewPutInventoryManufacturerManufacturerIDModelModelIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPutInventoryManufacturerManufacturerIDModelModelIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutInventoryManufacturerManufacturerIDModelModelIDNoContent creates a PutInventoryManufacturerManufacturerIDModelModelIDNoContent with default headers values
func NewPutInventoryManufacturerManufacturerIDModelModelIDNoContent() *PutInventoryManufacturerManufacturerIDModelModelIDNoContent {
	return &PutInventoryManufacturerManufacturerIDModelModelIDNoContent{}
}

/*PutInventoryManufacturerManufacturerIDModelModelIDNoContent handles this case with default header values.

No Content
*/
type PutInventoryManufacturerManufacturerIDModelModelIDNoContent struct {
}

func (o *PutInventoryManufacturerManufacturerIDModelModelIDNoContent) Error() string {
	return fmt.Sprintf("[PUT /inventory/manufacturer/{manufacturerId}/model/{modelId}][%d] putInventoryManufacturerManufacturerIdModelModelIdNoContent ", 204)
}

func (o *PutInventoryManufacturerManufacturerIDModelModelIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutInventoryManufacturerManufacturerIDModelModelIDBadRequest creates a PutInventoryManufacturerManufacturerIDModelModelIDBadRequest with default headers values
func NewPutInventoryManufacturerManufacturerIDModelModelIDBadRequest() *PutInventoryManufacturerManufacturerIDModelModelIDBadRequest {
	return &PutInventoryManufacturerManufacturerIDModelModelIDBadRequest{}
}

/*PutInventoryManufacturerManufacturerIDModelModelIDBadRequest handles this case with default header values.

Bad Request
*/
type PutInventoryManufacturerManufacturerIDModelModelIDBadRequest struct {
	Payload *models.Error
}

func (o *PutInventoryManufacturerManufacturerIDModelModelIDBadRequest) Error() string {
	return fmt.Sprintf("[PUT /inventory/manufacturer/{manufacturerId}/model/{modelId}][%d] putInventoryManufacturerManufacturerIdModelModelIdBadRequest  %+v", 400, o.Payload)
}

func (o *PutInventoryManufacturerManufacturerIDModelModelIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
