// Code generated by go-swagger; DO NOT EDIT.

package fleet_tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// DeleteFleetTenantTenantIDSystemPropertiesURLReader is a Reader for the DeleteFleetTenantTenantIDSystemPropertiesURL structure.
type DeleteFleetTenantTenantIDSystemPropertiesURLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteFleetTenantTenantIDSystemPropertiesURLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteFleetTenantTenantIDSystemPropertiesURLNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteFleetTenantTenantIDSystemPropertiesURLBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteFleetTenantTenantIDSystemPropertiesURLNoContent creates a DeleteFleetTenantTenantIDSystemPropertiesURLNoContent with default headers values
func NewDeleteFleetTenantTenantIDSystemPropertiesURLNoContent() *DeleteFleetTenantTenantIDSystemPropertiesURLNoContent {
	return &DeleteFleetTenantTenantIDSystemPropertiesURLNoContent{}
}

/*DeleteFleetTenantTenantIDSystemPropertiesURLNoContent handles this case with default header values.

No Content
*/
type DeleteFleetTenantTenantIDSystemPropertiesURLNoContent struct {
}

func (o *DeleteFleetTenantTenantIDSystemPropertiesURLNoContent) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/systemPropertiesUrl][%d] deleteFleetTenantTenantIdSystemPropertiesUrlNoContent ", 204)
}

func (o *DeleteFleetTenantTenantIDSystemPropertiesURLNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteFleetTenantTenantIDSystemPropertiesURLBadRequest creates a DeleteFleetTenantTenantIDSystemPropertiesURLBadRequest with default headers values
func NewDeleteFleetTenantTenantIDSystemPropertiesURLBadRequest() *DeleteFleetTenantTenantIDSystemPropertiesURLBadRequest {
	return &DeleteFleetTenantTenantIDSystemPropertiesURLBadRequest{}
}

/*DeleteFleetTenantTenantIDSystemPropertiesURLBadRequest handles this case with default header values.

Bad Request
*/
type DeleteFleetTenantTenantIDSystemPropertiesURLBadRequest struct {
	Payload *models.Error
}

func (o *DeleteFleetTenantTenantIDSystemPropertiesURLBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /fleet/tenant/{tenantId}/systemPropertiesUrl][%d] deleteFleetTenantTenantIdSystemPropertiesUrlBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteFleetTenantTenantIDSystemPropertiesURLBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
