// Code generated by go-swagger; DO NOT EDIT.

package fleet_tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteFleetTenantTenantIDParams creates a new DeleteFleetTenantTenantIDParams object
// with the default values initialized.
func NewDeleteFleetTenantTenantIDParams() *DeleteFleetTenantTenantIDParams {
	var ()
	return &DeleteFleetTenantTenantIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteFleetTenantTenantIDParamsWithTimeout creates a new DeleteFleetTenantTenantIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteFleetTenantTenantIDParamsWithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDParams {
	var ()
	return &DeleteFleetTenantTenantIDParams{

		timeout: timeout,
	}
}

// NewDeleteFleetTenantTenantIDParamsWithContext creates a new DeleteFleetTenantTenantIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteFleetTenantTenantIDParamsWithContext(ctx context.Context) *DeleteFleetTenantTenantIDParams {
	var ()
	return &DeleteFleetTenantTenantIDParams{

		Context: ctx,
	}
}

// NewDeleteFleetTenantTenantIDParamsWithHTTPClient creates a new DeleteFleetTenantTenantIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteFleetTenantTenantIDParamsWithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDParams {
	var ()
	return &DeleteFleetTenantTenantIDParams{
		HTTPClient: client,
	}
}

/*DeleteFleetTenantTenantIDParams contains all the parameters to send to the API endpoint
for the delete fleet tenant tenant ID operation typically these are written to a http.Request
*/
type DeleteFleetTenantTenantIDParams struct {

	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete fleet tenant tenant ID params
func (o *DeleteFleetTenantTenantIDParams) WithTimeout(timeout time.Duration) *DeleteFleetTenantTenantIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete fleet tenant tenant ID params
func (o *DeleteFleetTenantTenantIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete fleet tenant tenant ID params
func (o *DeleteFleetTenantTenantIDParams) WithContext(ctx context.Context) *DeleteFleetTenantTenantIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete fleet tenant tenant ID params
func (o *DeleteFleetTenantTenantIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID params
func (o *DeleteFleetTenantTenantIDParams) WithHTTPClient(client *http.Client) *DeleteFleetTenantTenantIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete fleet tenant tenant ID params
func (o *DeleteFleetTenantTenantIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTenantID adds the tenantID to the delete fleet tenant tenant ID params
func (o *DeleteFleetTenantTenantIDParams) WithTenantID(tenantID string) *DeleteFleetTenantTenantIDParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the delete fleet tenant tenant ID params
func (o *DeleteFleetTenantTenantIDParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteFleetTenantTenantIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
