// Code generated by go-swagger; DO NOT EDIT.

package fleet_tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFleetTenantTenantIDParams creates a new GetFleetTenantTenantIDParams object
// with the default values initialized.
func NewGetFleetTenantTenantIDParams() *GetFleetTenantTenantIDParams {
	var ()
	return &GetFleetTenantTenantIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFleetTenantTenantIDParamsWithTimeout creates a new GetFleetTenantTenantIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFleetTenantTenantIDParamsWithTimeout(timeout time.Duration) *GetFleetTenantTenantIDParams {
	var ()
	return &GetFleetTenantTenantIDParams{

		timeout: timeout,
	}
}

// NewGetFleetTenantTenantIDParamsWithContext creates a new GetFleetTenantTenantIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFleetTenantTenantIDParamsWithContext(ctx context.Context) *GetFleetTenantTenantIDParams {
	var ()
	return &GetFleetTenantTenantIDParams{

		Context: ctx,
	}
}

// NewGetFleetTenantTenantIDParamsWithHTTPClient creates a new GetFleetTenantTenantIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFleetTenantTenantIDParamsWithHTTPClient(client *http.Client) *GetFleetTenantTenantIDParams {
	var ()
	return &GetFleetTenantTenantIDParams{
		HTTPClient: client,
	}
}

/*GetFleetTenantTenantIDParams contains all the parameters to send to the API endpoint
for the get fleet tenant tenant ID operation typically these are written to a http.Request
*/
type GetFleetTenantTenantIDParams struct {

	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get fleet tenant tenant ID params
func (o *GetFleetTenantTenantIDParams) WithTimeout(timeout time.Duration) *GetFleetTenantTenantIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get fleet tenant tenant ID params
func (o *GetFleetTenantTenantIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get fleet tenant tenant ID params
func (o *GetFleetTenantTenantIDParams) WithContext(ctx context.Context) *GetFleetTenantTenantIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get fleet tenant tenant ID params
func (o *GetFleetTenantTenantIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get fleet tenant tenant ID params
func (o *GetFleetTenantTenantIDParams) WithHTTPClient(client *http.Client) *GetFleetTenantTenantIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get fleet tenant tenant ID params
func (o *GetFleetTenantTenantIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTenantID adds the tenantID to the get fleet tenant tenant ID params
func (o *GetFleetTenantTenantIDParams) WithTenantID(tenantID string) *GetFleetTenantTenantIDParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the get fleet tenant tenant ID params
func (o *GetFleetTenantTenantIDParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFleetTenantTenantIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
