// Code generated by go-swagger; DO NOT EDIT.

package fleet_tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// NewPostFleetTenantParams creates a new PostFleetTenantParams object
// with the default values initialized.
func NewPostFleetTenantParams() *PostFleetTenantParams {
	var ()
	return &PostFleetTenantParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostFleetTenantParamsWithTimeout creates a new PostFleetTenantParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostFleetTenantParamsWithTimeout(timeout time.Duration) *PostFleetTenantParams {
	var ()
	return &PostFleetTenantParams{

		timeout: timeout,
	}
}

// NewPostFleetTenantParamsWithContext creates a new PostFleetTenantParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostFleetTenantParamsWithContext(ctx context.Context) *PostFleetTenantParams {
	var ()
	return &PostFleetTenantParams{

		Context: ctx,
	}
}

// NewPostFleetTenantParamsWithHTTPClient creates a new PostFleetTenantParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostFleetTenantParamsWithHTTPClient(client *http.Client) *PostFleetTenantParams {
	var ()
	return &PostFleetTenantParams{
		HTTPClient: client,
	}
}

/*PostFleetTenantParams contains all the parameters to send to the API endpoint
for the post fleet tenant operation typically these are written to a http.Request
*/
type PostFleetTenantParams struct {

	/*Body*/
	Body *models.CreateFleetTenant

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post fleet tenant params
func (o *PostFleetTenantParams) WithTimeout(timeout time.Duration) *PostFleetTenantParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post fleet tenant params
func (o *PostFleetTenantParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post fleet tenant params
func (o *PostFleetTenantParams) WithContext(ctx context.Context) *PostFleetTenantParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post fleet tenant params
func (o *PostFleetTenantParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post fleet tenant params
func (o *PostFleetTenantParams) WithHTTPClient(client *http.Client) *PostFleetTenantParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post fleet tenant params
func (o *PostFleetTenantParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post fleet tenant params
func (o *PostFleetTenantParams) WithBody(body *models.CreateFleetTenant) *PostFleetTenantParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post fleet tenant params
func (o *PostFleetTenantParams) SetBody(body *models.CreateFleetTenant) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostFleetTenantParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
