// Code generated by go-swagger; DO NOT EDIT.

package fleet_tenant

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/extenda/fleet-manager-sdk-go/fleetmanager/models"
)

// NewPutFleetTenantTenantIDParams creates a new PutFleetTenantTenantIDParams object
// with the default values initialized.
func NewPutFleetTenantTenantIDParams() *PutFleetTenantTenantIDParams {
	var ()
	return &PutFleetTenantTenantIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutFleetTenantTenantIDParamsWithTimeout creates a new PutFleetTenantTenantIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutFleetTenantTenantIDParamsWithTimeout(timeout time.Duration) *PutFleetTenantTenantIDParams {
	var ()
	return &PutFleetTenantTenantIDParams{

		timeout: timeout,
	}
}

// NewPutFleetTenantTenantIDParamsWithContext creates a new PutFleetTenantTenantIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutFleetTenantTenantIDParamsWithContext(ctx context.Context) *PutFleetTenantTenantIDParams {
	var ()
	return &PutFleetTenantTenantIDParams{

		Context: ctx,
	}
}

// NewPutFleetTenantTenantIDParamsWithHTTPClient creates a new PutFleetTenantTenantIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutFleetTenantTenantIDParamsWithHTTPClient(client *http.Client) *PutFleetTenantTenantIDParams {
	var ()
	return &PutFleetTenantTenantIDParams{
		HTTPClient: client,
	}
}

/*PutFleetTenantTenantIDParams contains all the parameters to send to the API endpoint
for the put fleet tenant tenant ID operation typically these are written to a http.Request
*/
type PutFleetTenantTenantIDParams struct {

	/*Body*/
	Body *models.UpdateFleetTenant
	/*TenantID*/
	TenantID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put fleet tenant tenant ID params
func (o *PutFleetTenantTenantIDParams) WithTimeout(timeout time.Duration) *PutFleetTenantTenantIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put fleet tenant tenant ID params
func (o *PutFleetTenantTenantIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put fleet tenant tenant ID params
func (o *PutFleetTenantTenantIDParams) WithContext(ctx context.Context) *PutFleetTenantTenantIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put fleet tenant tenant ID params
func (o *PutFleetTenantTenantIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put fleet tenant tenant ID params
func (o *PutFleetTenantTenantIDParams) WithHTTPClient(client *http.Client) *PutFleetTenantTenantIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put fleet tenant tenant ID params
func (o *PutFleetTenantTenantIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put fleet tenant tenant ID params
func (o *PutFleetTenantTenantIDParams) WithBody(body *models.UpdateFleetTenant) *PutFleetTenantTenantIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put fleet tenant tenant ID params
func (o *PutFleetTenantTenantIDParams) SetBody(body *models.UpdateFleetTenant) {
	o.Body = body
}

// WithTenantID adds the tenantID to the put fleet tenant tenant ID params
func (o *PutFleetTenantTenantIDParams) WithTenantID(tenantID string) *PutFleetTenantTenantIDParams {
	o.SetTenantID(tenantID)
	return o
}

// SetTenantID adds the tenantId to the put fleet tenant tenant ID params
func (o *PutFleetTenantTenantIDParams) SetTenantID(tenantID string) {
	o.TenantID = tenantID
}

// WriteToRequest writes these params to a swagger request
func (o *PutFleetTenantTenantIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param tenantId
	if err := r.SetPathParam("tenantId", o.TenantID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
